name: easy_gap
description: Add gaps between widgets in Flutter easily and flexibly - via extension methods or constructors for Flex widgets and scrolling views.
version: 1.1.0
homepage: "https://github.com/pavluke/easy_gap"
repository: "https://github.com/pavluke/easy_gap"
issue_tracker: "https://github.com/pavluke/easy_gap/issues"

environment:
  sdk: ^3.3.4
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

topics:
  - spacing
  - gap
  - widget
  - utility
  - extension
